name: GitHub Pages Deploy Client
on:
  push:
    branches:
      - main
    paths:
      - "**/client/**"
jobs:
  deploy:
    name: Deploy client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: yarn install
      - run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          yarn deploy
        env:
          PUBLIC_API_URL: https://ensemble.fly.dev
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
